### ISSUE TITLE
22-12-26 Meeting

### ISSUE THREAD

**Issue by DQ-Kwon** [DQ-Kwon/CS-Study-for-Tech-Interview#2]
Network Study 주간입니다.

**Comment by nanalyee** [comment]
📔 네트워크와 모델
1. 네트워크, 인터넷, 프로토콜의 개념을 설명해주세요.
2. 네트워크 통신방식 3가지를 설명하고 해당 통신방식에 속하는 예시를 하나 설명해주세요.
3. 네트워크 모델 2가지를 설명하고 두 모델의 공통점과 차이점을 설명해주세요.

**Comment by nanalyee** [comment]
📔 데이터 통신
1. Ethernet에 대해 설명하세요.
2. LAN에 대해 설명하세요.
3. 데이터 링크 계층의 역할에 대해 설명하세요.

**Comment by nanalyee** [comment]
📔 IP 주소
1. 공인 IP와 사설 IP의 차이에 대해서 설명해주세요.
2. IPv4 와 IPv6의 차이는?
3. 서브넷 마스크에 대해서 설명해주세요.
4. IP 주소 클래스에 대해서 설명해주세요.

**Comment by nanalyee** [comment]
📔 ARP 프로토콜
1. ARP 프로토콜 동작 흐름에 대해 설명해주세요. (ARP 프로토콜에 대해 설명해주세요.)
2. ARP와 RARP를 비교해서 설명해주세요.

**Comment by nanalyee** [comment]
📔 IPv4, ICMP 프로토콜
1. IPv4가 하는일과 IPv4 프로토콜 구조를 설명해주세요.
2. ICMP가 하는일과 ICMP 프로토콜 구조를 설명해주세요.
3. 다른 네트워크까지 내 패킷의 이동 과정을 설명해주세요.

**Comment by nanalyee** [comment]
📔 전송계층 및 포트
1. Port란 무엇인가요?
2. 서버 측에서 사용되는 포트는 이미 정해져 있습니다. 주요 Well-Known Port에 대해 아는대로 설명해주세요.
3. 클라이언트와 서버의 통신 과정에 대해 설명해주세요.

**Comment by nanalyee** [comment]
📔 UDP 비연결지향형
1. UDP 서버의 특징에 대해서 설명하세요.
2. UDP는 어느 상황에서 사용하는지 설명하세요.

**Comment by nanalyee** [comment]
📔 TCP 연결지향형

1. TCP 프로토콜의 특징을 UDP 프로토콜과 비교하여 설명해주세요.
2. 3-way handshake에 대해 설명해주세요.
3. 3-way handshake에서 클라이언트가 서버가 보낸 ACK+SYC을 받지 못하면 어떻게 되나요?
4. 4-way handshake에서 서버가 마지막에 FIN을 보내는 이유는 무엇인가요?
5. 4-way handshake에서 클라이언트가 마지막에 ACK를 보내는 이유는 무엇인가요?

**Comment by nanalyee** [comment]
📔 NAT와 포트포워딩
1. NAT란 무엇인지 설명해주세요.
2. 포트포워딩이란 무엇인지 설명해주세요.

**Comment by nanalyee** [comment]
📔 HTTP 프로토콜
1. HTTP와 HTTPS의 차이에 대해 설명하세요.
2. HTTP의 GET 방식과 POST 방식을 비교해주세요.
3. HTTP의 Statue Code의 종류는 어떻게 되나요?
4. 주소창에 URL을 치고 엔터를 치면 흐름이 어떻게 되나요?

**Comment by nanalyee** [comment]
📔 기타
1. CORS란 무엇인가요?
2. CORS 에러가 발생하는 원인을 SOP와 관련하여 설명해주세요.
3. 쿠키와 세션의 차이점에 대해 설명해주세요.
4. 프록시와 프록시 서버에 대해 설명해주세요.
5. JWT 에 대해서 설명해주세요.

**Comment by DQ-Kwon** [comment]
📔 기타
  1. www.naver.com에 접속할 때 생기는 과정에 대해 설명해주세요. 
  2. 공인(public) IP와 사설(private) IP의 차이에 대해 설명해주세요.
  3. OSI 7 layer와 각 계층에 대해 아는대로 설명해주세요.
  4. 세션 기반 인증과 토큰 기반 인증의 차이에 대해 얘기해주세요.
  5. 그렇다면 Stateful한 세션 기반의 인증 방식을 사용하게 된다면 어떠한 단점이 있을까요?
  6. 그렇다면 세션 기반 인증과 토큰 기반 인증은 각각 어느 경우에 적합한가요?
